In [1]:
import os
import pandas as pd
import re

# Ruta de la carpeta de datos
data_folder = 'data'

# Lista para almacenar los DataFrames
dfs = []

# Iterar sobre los archivos en la carpeta
for filename in os.listdir(data_folder):
    if filename.endswith('.xlsx') and 'key_operational_metrics' in filename:
        file_path = os.path.join(data_folder, filename)
        df = pd.read_excel(file_path)
        #df['nombre_archivo'] = filename  # Agrega columna con el nombre del archivo
        # Extrae año (20xx) y Q (q1, q2, q3, q4) del nombre del archivo
        match = re.search(r'(20\d{2})', filename)
        year = match.group(1) if match else ''
        match_q = re.search(r'(q[1-4])', filename, re.IGNORECASE)
        q = match_q.group(1).upper() if match_q else ''
        df['anio_q'] = year +" "+ q
        dfs.append(df)

# dfs contiene todos los DataFrames importados, cada uno con las columnas 'nombre_archivo', 'anio' y 'trimestre'

In [2]:
dfs1 = []
import re

palabras_clave = ["Métrica", "nombre", "Key Metric","nombre de la métrica","Metric"]

for i, df in enumerate(dfs):
   # print(df.columns)
   # print(df.head())
    
    valor_anio_q = str(df["anio_q"].iloc[0]).strip()
    # Extraer año y Q
    match = re.search(r'(\d{4})\s*[-_ ]?\s*(Q\d)', valor_anio_q, re.IGNORECASE)
    if match:
        anio = match.group(1)
        q = match.group(2).upper()
    else:
        print(f"No se pudo extraer año y Q de '{valor_anio_q}'")
        continue
    
    # Buscar columnas que contengan tanto el año como el Q
    cols_q_anio = [col for col in df.columns if anio in col and q in col.upper()]
    
    # Columnas de métricas
    cols_metricas = [col for col in df.columns if any(p.lower() in col.lower() for p in palabras_clave)]
    
    columnas_deseadas = cols_metricas + cols_q_anio# +["anio_q"]
    print(f"DataFrame {i+1} - Columnas seleccionadas: {columnas_deseadas}")
    df_filtrado = df[columnas_deseadas].copy()
    df_filtrado = df_filtrado.rename(columns={df_filtrado.columns[0]: "Metric"})

    print(df[columnas_deseadas].head())
    dfs1.append(df_filtrado)

DataFrame 1 - Columnas seleccionadas: ['Métrica', 'Q4 2021']
                   Métrica Q4 2021
0           Ore mined (kt)     864
1         Waste mined (kt)   8,972
2  Strip ratio (waste:ore)    10.4
3         Gold grade (g/t)    2.75
4           Ore mined (kt)      95
DataFrame 2 - Columnas seleccionadas: ['nombre de la métrica', 'Q3 2022']
      nombre de la métrica Q3 2022
0           Ore mined (kt)     883
1         Waste mined (kt)   9,097
2  Strip ratio (waste:ore)    10.3
3         Gold grade (g/t)    3.02
4           Ore mined (kt)     143
DataFrame 3 - Columnas seleccionadas: ['nombre', 'Q4 2022']
                             nombre Q4 2022
0     Ore mined (kt) - ELG Open Pit     959
1                  Waste mined (kt)   8,546
2           Strip ratio (waste:ore)     8.9
3   Gold grade (g/t) - ELG Open Pit    3.06
4  Ore mined (kt) - ELG Underground     155
DataFrame 4 - Columnas seleccionadas: ['nombre de la métrica', 'Q3 2023']
                              nombre de la métrica Q3 2023
0           Ore mined (kt) - Mining - ELG Open Pit   1,026
1          Ore mined (tpd) - Mining - ELG Open Pit  11,153
2         Waste mined (kt) - Mining - ELG Open Pit  10,131
3  Strip ratio (waste:ore) - Mining - ELG Open Pit     9.9
4         Gold grade (gpt) - Mining - ELG Open Pit    1.84
DataFrame 5 - Columnas seleccionadas: ['Metric', 'Q1 2023']
                                     Metric Q1 2023
0    Ore mined (kt) - Mining - ELG Open Pit     916
1   Ore mined (tpd) - Mining - ELG Open Pit  10,182
2                          Waste mined (kt)   8,437
3                   Strip ratio (waste:ore)     9.2
4  Gold grade (gpt) - Mining - ELG Open Pit    4.31
DataFrame 6 - Columnas seleccionadas: ['nombre', 'Q2 2024']
                    nombre Q2 2024
0           Ore mined (kt)   1,622
1          Ore mined (tpd)  17,822
2         Waste mined (kt)   7,047
3  Strip ratio (waste:ore)     4.3
4         Gold grade (gpt)    2.61
DataFrame 7 - Columnas seleccionadas: ['métrica', 'Q1 2024']
                   métrica Q1 2024
0           Ore mined (kt)     969
1          Ore mined (tpd)  10,651
2         Waste mined (kt)   8,012
3  Strip ratio (waste:ore)     8.3
4         Gold grade (gpt)    2.74
DataFrame 8 - Columnas seleccionadas: ['nombre de la métrica']
      nombre de la métrica
0           Ore mined (kt)
1          Ore mined (tpd)
2         Waste mined (kt)
3  Strip ratio (waste:ore)
4         Gold grade (gpt)
DataFrame 9 - Columnas seleccionadas: ['nombre', 'Q2 2021']
                         nombre Q2 2021
0     Ore mined (kt) - Open Pit   1,131
1              Waste mined (kt)   8,593
2       Strip ratio (waste:ore)     7.6
3   Gold grade (g/t) - Open Pit    3.01
4  Ore mined (kt) - Underground     130
DataFrame 10 - Columnas seleccionadas: ['nombre']
    nombre
0  Q4 2019
1  Q1 2020
2  Q2 2020
3  Q3 2020
4  Q4 2020
DataFrame 11 - Columnas seleccionadas: ['nombre de la métrica', 'Q4 2023']
                     nombre de la métrica Q4 2023
0           Ore mined (kt) - ELG Open Pit   1,785
1          Ore mined (tpd) - ELG Open Pit  19,404
2         Waste mined (kt) - ELG Open Pit   7,841
3  Strip ratio (waste:ore) - ELG Open Pit     4.4
4         Gold grade (gpt) - ELG Open Pit    2.66
DataFrame 12 - Columnas seleccionadas: ['nombre', 'Q1 2022']
                       nombre Q1 2022
0              Ore mined (kt)   1,061
1            Waste mined (kt)   8,958
2     Strip ratio (waste:ore)     8.4
3            Gold grade (g/t)    2.99
4  Ore mined (kt) Underground     114
DataFrame 13 - Columnas seleccionadas: ['métrica', 'Q2 2022']
                            métrica Q2 2022
0     Ore mined (kt) - ELG Open Pit     987
1                  Waste mined (kt)   7,960
2           Strip ratio (waste:ore)     8.1
3   Gold grade (g/t) - ELG Open Pit    3.58
4  Ore mined (kt) - ELG Underground     144
DataFrame 14 - Columnas seleccionadas: ['nombre_metrica', 'Q2 2023']
                           nombre_metrica Q2 2023
0           Ore mined (kt) - ELG Open Pit     644
1          Ore mined (tpd) - ELG Open Pit   7,074
2         Waste mined (kt) - ELG Open Pit  11,124
3  Strip ratio (waste:ore) - ELG Open Pit    17.3
4         Gold grade (gpt) - ELG Open Pit    2.72
DataFrame 15 - Columnas seleccionadas: ['Metric', 'Q3 2024']
                    Metric Q3 2024
0           Ore mined (kt)   1,539
1          Ore mined (tpd)  16,731
2         Waste mined (kt)   4,299
3  Strip ratio (waste:ore)     2.8
4         Gold grade (gpt)    2.72

In [3]:
for i in range(len(dfs1)):
    print(i)
    print(dfs1[i].head(2))
    print(dfs1[i]["Metric"])

0
             Metric Q4 2021
0    Ore mined (kt)     864
1  Waste mined (kt)   8,972
0              Ore mined (kt)
1            Waste mined (kt)
2     Strip ratio (waste:ore)
3            Gold grade (g/t)
4              Ore mined (kt)
5            Gold grade (g/t)
6              Ore mined (kt)
7            Gold grade (g/t)
8          Ore processed (kt)
9         Ore processed (tpd)
10           Gold grade (g/t)
11          Gold recovery (%)
12         Gold produced (oz)
13             Gold sold (oz)
Name: Metric, dtype: object
1
             Metric Q3 2022
0    Ore mined (kt)     883
1  Waste mined (kt)   9,097
0              Ore mined (kt)
1            Waste mined (kt)
2     Strip ratio (waste:ore)
3            Gold grade (g/t)
4              Ore mined (kt)
5            Gold grade (g/t)
6              Ore mined (kt)
7            Gold grade (g/t)
8          Ore processed (kt)
9         Ore processed (tpd)
10           Gold grade (g/t)
11          Gold recovery (%)
12         Gold produced (oz)
13             Gold sold (oz)
Name: Metric, dtype: object
2
                          Metric Q4 2022
0  Ore mined (kt) - ELG Open Pit     959
1               Waste mined (kt)   8,546
0          Ore mined (kt) - ELG Open Pit
1                       Waste mined (kt)
2                Strip ratio (waste:ore)
3        Gold grade (g/t) - ELG Open Pit
4       Ore mined (kt) - ELG Underground
5     Gold grade (g/t) - ELG Underground
6                 Ore mined (kt) - Total
7               Gold grade (g/t) - Total
8                     Ore processed (kt)
9                    Ore processed (tpd)
10         Gold grade (g/t) - Processing
11                     Gold recovery (%)
12                    Gold produced (oz)
13                        Gold sold (oz)
Name: Metric, dtype: object
3
                                    Metric Q3 2023
0   Ore mined (kt) - Mining - ELG Open Pit   1,026
1  Ore mined (tpd) - Mining - ELG Open Pit  11,153
0              Ore mined (kt) - Mining - ELG Open Pit
1             Ore mined (tpd) - Mining - ELG Open Pit
2            Waste mined (kt) - Mining - ELG Open Pit
3     Strip ratio (waste:ore) - Mining - ELG Open Pit
4            Gold grade (gpt) - Mining - ELG Open Pit
5           Ore mined (kt) - Mining - ELG Underground
6          Ore mined (tpd) - Mining - ELG Underground
7         Gold grade (gpt) - Mining - ELG Underground
8                     Ore mined (kt) - Mining - Total
9                    Ore mined (tpd) - Mining - Total
10                  Gold grade (gpt) - Mining - Total
11                    Ore processed (kt) - Processing
12                   Ore processed (tpd) - Processing
13                      Gold grade (gpt) - Processing
14                     Gold recovery (%) - Processing
15                    Gold produced (oz) - Processing
16                        Gold sold (oz) - Processing
Name: Metric, dtype: object
4
                                    Metric Q1 2023
0   Ore mined (kt) - Mining - ELG Open Pit     916
1  Ore mined (tpd) - Mining - ELG Open Pit  10,182
0          Ore mined (kt) - Mining - ELG Open Pit
1         Ore mined (tpd) - Mining - ELG Open Pit
2                                Waste mined (kt)
3                         Strip ratio (waste:ore)
4        Gold grade (gpt) - Mining - ELG Open Pit
5       Ore mined (kt) - Mining - ELG Underground
6      Ore mined (tpd) - Mining - ELG Underground
7     Gold grade (gpt) - Mining - ELG Underground
8                 Ore mined (kt) - Mining - Total
9                Ore mined (tpd) - Mining - Total
10              Gold grade (gpt) - Mining - Total
11                             Ore processed (kt)
12                            Ore processed (tpd)
13                  Gold grade (gpt) - Processing
14                              Gold recovery (%)
15                             Gold produced (oz)
16                                 Gold sold (oz)
Name: Metric, dtype: object
5
            Metric Q2 2024
0   Ore mined (kt)   1,622
1  Ore mined (tpd)  17,822
0                         Ore mined (kt)
1                        Ore mined (tpd)
2                       Waste mined (kt)
3                Strip ratio (waste:ore)
4                       Gold grade (gpt)
5                         Ore mined (kt)
6                        Ore mined (tpd)
7                       Gold grade (gpt)
8                         Ore mined (kt)
9                        Ore mined (tpd)
10                      Gold grade (gpt)
11                    Ore processed (kt)
12                   Ore processed (tpd)
13                      Gold grade (gpt)
14                     Gold recovery (%)
15                    Gold produced (oz)
16                        Gold sold (oz)
17    Gold equivalent produced (oz AuEq)
18        Gold equivalent sold (oz AuEq)
Name: Metric, dtype: object
6
            Metric Q1 2024
0   Ore mined (kt)     969
1  Ore mined (tpd)  10,651
0                         Ore mined (kt)
1                        Ore mined (tpd)
2                       Waste mined (kt)
3                Strip ratio (waste:ore)
4                       Gold grade (gpt)
5                         Ore mined (kt)
6                        Ore mined (tpd)
7                       Gold grade (gpt)
8                         Ore mined (kt)
9                        Ore mined (tpd)
10                      Gold grade (gpt)
11                    Ore processed (kt)
12                   Ore processed (tpd)
13                      Gold grade (gpt)
14                     Gold recovery (%)
15                    Gold produced (oz)
16                        Gold sold (oz)
17    Gold equivalent produced (oz AuEq)
18        Gold equivalent sold (oz AuEq)
Name: Metric, dtype: object
7
            Metric
0   Ore mined (kt)
1  Ore mined (tpd)
0                          Ore mined (kt)
1                         Ore mined (tpd)
2                        Waste mined (kt)
3                 Strip ratio (waste:ore)
4                        Gold grade (gpt)
5                          Ore mined (kt)
6                         Ore mined (tpd)
7                        Gold grade (gpt)
8                          Ore mined (kt)
9                         Ore mined (tpd)
10                       Gold grade (gpt)
11                         Ore mined (kt)
12                     Ore processed (kt)
13                    Ore processed (tpd)
14                       Gold grade (gpt)
15                      Gold recovery (%)
16                    Gold produced (koz)
17                        Gold sold (koz)
18    Gold equivalent produced (koz AuEq)
19        Gold equivalent sold (koz AuEq)
Name: Metric, dtype: object
8
                      Metric Q2 2021
0  Ore mined (kt) - Open Pit   1,131
1           Waste mined (kt)   8,593
0          Ore mined (kt) - Open Pit
1                   Waste mined (kt)
2            Strip ratio (waste:ore)
3        Gold grade (g/t) - Open Pit
4       Ore mined (kt) - Underground
5     Gold grade (g/t) - Underground
6             Ore mined (kt) - Total
7           Gold grade (g/t) - Total
8                 Ore processed (kt)
9                Ore processed (tpd)
10     Gold grade (g/t) - Processing
11                 Gold recovery (%)
12                Gold produced (oz)
13                    Gold sold (oz)
Name: Metric, dtype: object
9
    Metric
0  Q4 2019
1  Q1 2020
0    Q4 2019
1    Q1 2020
2    Q2 2020
3    Q3 2020
4    Q4 2020
5    Q1 2021
6    Q2 2021
7    Q3 2021
Name: Metric, dtype: object
10
                           Metric Q4 2023
0   Ore mined (kt) - ELG Open Pit   1,785
1  Ore mined (tpd) - ELG Open Pit  19,404
0              Ore mined (kt) - ELG Open Pit
1             Ore mined (tpd) - ELG Open Pit
2            Waste mined (kt) - ELG Open Pit
3     Strip ratio (waste:ore) - ELG Open Pit
4            Gold grade (gpt) - ELG Open Pit
5           Ore mined (kt) - ELG Underground
6          Ore mined (tpd) - ELG Underground
7         Gold grade (gpt) - ELG Underground
8                     Ore mined (kt) - Total
9                    Ore mined (tpd) - Total
10                  Gold grade (gpt) - Total
11           Ore processed (kt) - Processing
12          Ore processed (tpd) - Processing
13             Gold grade (gpt) - Processing
14            Gold recovery (%) - Processing
15           Gold produced (oz) - Processing
16               Gold sold (oz) - Processing
Name: Metric, dtype: object
11
             Metric Q1 2022
0    Ore mined (kt)   1,061
1  Waste mined (kt)   8,958
0                   Ore mined (kt)
1                 Waste mined (kt)
2          Strip ratio (waste:ore)
3                 Gold grade (g/t)
4       Ore mined (kt) Underground
5     Gold grade (g/t) Underground
6             Ore mined (kt) Total
7           Gold grade (g/t) Total
8               Ore processed (kt)
9              Ore processed (tpd)
10     Gold grade (g/t) Processing
11               Gold recovery (%)
12              Gold produced (oz)
13                  Gold sold (oz)
Name: Metric, dtype: object
12
                          Metric Q2 2022
0  Ore mined (kt) - ELG Open Pit     987
1               Waste mined (kt)   7,960
0          Ore mined (kt) - ELG Open Pit
1                       Waste mined (kt)
2                Strip ratio (waste:ore)
3        Gold grade (g/t) - ELG Open Pit
4       Ore mined (kt) - ELG Underground
5     Gold grade (g/t) - ELG Underground
6                 Ore mined (kt) - Total
7               Gold grade (g/t) - Total
8                     Ore processed (kt)
9                    Ore processed (tpd)
10         Gold grade (g/t) - Processing
11                     Gold recovery (%)
12                    Gold produced (oz)
13                        Gold sold (oz)
Name: Metric, dtype: object
13
                           Metric Q2 2023
0   Ore mined (kt) - ELG Open Pit     644
1  Ore mined (tpd) - ELG Open Pit   7,074
0              Ore mined (kt) - ELG Open Pit
1             Ore mined (tpd) - ELG Open Pit
2            Waste mined (kt) - ELG Open Pit
3     Strip ratio (waste:ore) - ELG Open Pit
4            Gold grade (gpt) - ELG Open Pit
5           Ore mined (kt) - ELG Underground
6          Ore mined (tpd) - ELG Underground
7         Gold grade (gpt) - ELG Underground
8                     Ore mined (kt) - Total
9                    Ore mined (tpd) - Total
10                  Gold grade (gpt) - Total
11           Ore processed (kt) - Processing
12          Ore processed (tpd) - Processing
13             Gold grade (gpt) - Processing
14            Gold recovery (%) - Processing
15           Gold produced (oz) - Processing
16               Gold sold (oz) - Processing
Name: Metric, dtype: object
14
            Metric Q3 2024
0   Ore mined (kt)   1,539
1  Ore mined (tpd)  16,731
0                         Ore mined (kt)
1                        Ore mined (tpd)
2                       Waste mined (kt)
3                Strip ratio (waste:ore)
4                       Gold grade (gpt)
5                         Ore mined (kt)
6                        Ore mined (tpd)
7                       Gold grade (gpt)
8                         Ore mined (kt)
9                        Ore mined (tpd)
10                      Gold grade (gpt)
11                    Ore processed (kt)
12                   Ore processed (tpd)
13                      Gold grade (gpt)
14                     Gold recovery (%)
15                    Gold produced (oz)
16                        Gold sold (oz)
17    Gold equivalent produced (oz AuEq)
18        Gold equivalent sold (oz AuEq)
Name: Metric, dtype: object

In [4]:

#Edfs_alineados = [df.set_index("Metric") for df in dfs1]
##df_concat = pd.concat(dfs_alineados, axis=1)
#df_concat.head()

# Concatenar los DataFrames de dfs1 de forma horizontal (por columnas)
df_concat = pd.concat(dfs1, axis=1)

# Mostrar las primeras filas del DataFrame resultante
df_concat.head()

,Metric,Q4 2021,Metric,Q3 2022,Metric,Q4 2022,Metric,Q3 2023,Metric,Q1 2023,...,Metric,Q4 2023,Metric,Q1 2022,Metric,Q2 2022,Metric,Q2 2023,Metric,Q3 2024
0,Ore mined (kt),864,Ore mined (kt),883,Ore mined (kt) - ELG Open Pit,959,Ore mined (kt) - Mining - ELG Open Pit,"1,026",Ore mined (kt) - Mining - ELG Open Pit,916,...,Ore mined (kt) - ELG Open Pit,"1,785",Ore mined (kt),"1,061",Ore mined (kt) - ELG Open Pit,987,Ore mined (kt) - ELG Open Pit,644,Ore mined (kt),"1,539"
1,Waste mined (kt),"8,972",Waste mined (kt),"9,097",Waste mined (kt),"8,546",Ore mined (tpd) - Mining - ELG Open Pit,"11,153",Ore mined (tpd) - Mining - ELG Open Pit,"10,182",...,Ore mined (tpd) - ELG Open Pit,"19,404",Waste mined (kt),"8,958",Waste mined (kt),"7,960",Ore mined (tpd) - ELG Open Pit,"7,074",Ore mined (tpd),"16,731"
2,Strip ratio (waste:ore),10.4,Strip ratio (waste:ore),10.3,Strip ratio (waste:ore),8.9,Waste mined (kt) - Mining - ELG Open Pit,"10,131",Waste mined (kt),"8,437",...,Waste mined (kt) - ELG Open Pit,"7,841",Strip ratio (waste:ore),8.4,Strip ratio (waste:ore),8.1,Waste mined (kt) - ELG Open Pit,"11,124",Waste mined (kt),"4,299"
3,Gold grade (g/t),2.75,Gold grade (g/t),3.02,Gold grade (g/t) - ELG Open Pit,3.06,Strip ratio (waste:ore) - Mining - ELG Open Pit,9.9,Strip ratio (waste:ore),9.2,...,Strip ratio (waste:ore) - ELG Open Pit,4.4,Gold grade (g/t),2.99,Gold grade (g/t) - ELG Open Pit,3.58,Strip ratio (waste:ore) - ELG Open Pit,17.3,Strip ratio (waste:ore),2.8
4,Ore mined (kt),95,Ore mined (kt),143,Ore mined (kt) - ELG Underground,155,Gold grade (gpt) - Mining - ELG Open Pit,1.84,Gold grade (gpt) - Mining - ELG Open Pit,4.31,...,Gold grade (gpt) - ELG Open Pit,2.66,Ore mined (kt) Underground,114,Ore mined (kt) - ELG Underground,144,Gold grade (gpt) - ELG Open Pit,2.72,Gold grade (gpt),2.72

In [5]:
import re

# Encuentra las columnas que corresponden a trimestres (formato QX YYYY)
quarter_cols = [col for col in df_concat.columns if re.match(r'Q[1-4] \d{4}', str(col))]

# Ordena las columnas de los trimestres cronológicamente
quarter_cols_sorted = sorted(
    quarter_cols,
    key=lambda x: (int(x.split()[1]), int(x.split()[0][1]))
)

# Reordena el DataFrame: primero 'Metric', luego los trimestres ordenados, luego el resto
cols_order = (
    ['Metric'] +
    quarter_cols_sorted 
)
df_concat = df_concat[cols_order]

In [6]:
df_concat.head()

,Metric,Metric,Metric,Metric,Metric,Metric,Metric,Metric,Metric,Metric,...,Q2 2022,Q3 2022,Q4 2022,Q1 2023,Q2 2023,Q3 2023,Q4 2023,Q1 2024,Q2 2024,Q3 2024
0,Ore mined (kt),Ore mined (kt),Ore mined (kt) - ELG Open Pit,Ore mined (kt) - Mining - ELG Open Pit,Ore mined (kt) - Mining - ELG Open Pit,Ore mined (kt),Ore mined (kt),Ore mined (kt),Ore mined (kt) - Open Pit,Q4 2019,...,987,883,959,916,644,"1,026","1,785",969,"1,622","1,539"
1,Waste mined (kt),Waste mined (kt),Waste mined (kt),Ore mined (tpd) - Mining - ELG Open Pit,Ore mined (tpd) - Mining - ELG Open Pit,Ore mined (tpd),Ore mined (tpd),Ore mined (tpd),Waste mined (kt),Q1 2020,...,"7,960","9,097","8,546","10,182","7,074","11,153","19,404","10,651","17,822","16,731"
2,Strip ratio (waste:ore),Strip ratio (waste:ore),Strip ratio (waste:ore),Waste mined (kt) - Mining - ELG Open Pit,Waste mined (kt),Waste mined (kt),Waste mined (kt),Waste mined (kt),Strip ratio (waste:ore),Q2 2020,...,8.1,10.3,8.9,"8,437","11,124","10,131","7,841","8,012","7,047","4,299"
3,Gold grade (g/t),Gold grade (g/t),Gold grade (g/t) - ELG Open Pit,Strip ratio (waste:ore) - Mining - ELG Open Pit,Strip ratio (waste:ore),Strip ratio (waste:ore),Strip ratio (waste:ore),Strip ratio (waste:ore),Gold grade (g/t) - Open Pit,Q3 2020,...,3.58,3.02,3.06,9.2,17.3,9.9,4.4,8.3,4.3,2.8
4,Ore mined (kt),Ore mined (kt),Ore mined (kt) - ELG Underground,Gold grade (gpt) - Mining - ELG Open Pit,Gold grade (gpt) - Mining - ELG Open Pit,Gold grade (gpt),Gold grade (gpt),Gold grade (gpt),Ore mined (kt) - Underground,Q4 2020,...,144,143,155,4.31,2.72,1.84,2.66,2.74,2.61,2.72