In [1]:
import os
import pandas as pd
import re

# Ruta de la carpeta de datos
data_folder = 'data'

# Lista para almacenar los DataFrames
dfs = []

# Iterar sobre los archivos en la carpeta
for filename in os.listdir(data_folder):
    if filename.endswith('.xlsx') and 'key_financial_metrics' in filename:
        file_path = os.path.join(data_folder, filename)
        df = pd.read_excel(file_path)
        #df['nombre_archivo'] = filename  # Agrega columna con el nombre del archivo
        # Extrae año (20xx) y Q (q1, q2, q3, q4) del nombre del archivo
        match = re.search(r'(20\d{2})', filename)
        year = match.group(1) if match else ''
        match_q = re.search(r'(q[1-4])', filename, re.IGNORECASE)
        q = match_q.group(1).upper() if match_q else ''
        df['anio_q'] = year +" "+ q
        dfs.append(df)

# dfs contiene todos los DataFrames importados, cada uno con las columnas 'nombre_archivo', 'anio' y 'trimestre'

In [2]:
dfs1 = []
import re

palabras_clave = ["Métrica", "nombre", "Key Metric","nombre de la métrica","Metric"]

for i, df in enumerate(dfs):
   # print(df.columns)
   # print(df.head())
    
    valor_anio_q = str(df["anio_q"].iloc[0]).strip()
    # Extraer año y Q
    match = re.search(r'(\d{4})\s*[-_ ]?\s*(Q\d)', valor_anio_q, re.IGNORECASE)
    if match:
        anio = match.group(1)
        q = match.group(2).upper()
    else:
        print(f"No se pudo extraer año y Q de '{valor_anio_q}'")
        continue
    
    # Buscar columnas que contengan tanto el año como el Q
    cols_q_anio = [col for col in df.columns if anio in col and q in col.upper()]
    
    # Columnas de métricas
    cols_metricas = [col for col in df.columns if any(p.lower() in col.lower() for p in palabras_clave)]
    
    columnas_deseadas = cols_metricas + cols_q_anio# +["anio_q"]
    print(f"DataFrame {i+1} - Columnas seleccionadas: {columnas_deseadas}")
    df_filtrado = df[columnas_deseadas].copy()
    df_filtrado = df_filtrado.rename(columns={df_filtrado.columns[0]: "Metric"})

    print(df[columnas_deseadas].head())
    dfs1.append(df_filtrado)

DataFrame 1 - Columnas seleccionadas: ['Metric', 'Q4 2021']
                          Metric  Q4 2021
0                 Gold sold (oz)  109,391
1     Realized gold price ($/oz)   $1,798
2           Cost of sales ($/oz)   $1,235
3         Total cash cost ($/oz)     $764
4  All-in sustaining cost ($/oz)   $1,079
DataFrame 2 - Columnas seleccionadas: ['nombre de la métrica', 'Q3 2022']
             nombre de la métrica  Q3 2022
0                  Gold sold (oz)  119,834
1      Realized gold price ($/oz)   $1,715
2            Cost of sales ($/oz)   $1,220
3         Total cash costs ($/oz)     $760
4  All-in sustaining costs ($/oz)   $1,059
DataFrame 3 - Columnas seleccionadas: ['nombre', 'Q4 2022']
                           nombre  Q4 2022
0                  Gold sold (oz)  121,913
1      Realized gold price ($/oz)   $1,784
2            Cost of sales ($/oz)   $1,202
3         Total cash costs ($/oz)     $711
4  All-in sustaining costs ($/oz)   $1,034
DataFrame 4 - Columnas seleccionadas: ['métrica', 'Q3 2023']
                          métrica Q3 2023
0                  Gold sold (oz)  81,752
1      Realized gold price ($/oz)  $1,944
2            Cost of sales ($/oz)  $1,627
3         Total cash costs ($/oz)  $1,086
4  All-in sustaining costs ($/oz)  $1,450
DataFrame 5 - Columnas seleccionadas: ['nombre de la métrica', 'Q1 2023']
             nombre de la métrica  Q1 2023
0                  Gold sold (oz)  118,455
1      Realized gold price ($/oz)   $1,899
2            Cost of sales ($/oz)   $1,160
3         Total cash costs ($/oz)     $709
4  All-in sustaining costs ($/oz)   $1,079
DataFrame 6 - Columnas seleccionadas: ['nombre', 'Q2 2024']
                               nombre  Q2 2024
0                      Gold sold (oz)  113,513
1      Gold equivalent sold (oz AuEq)  115,890
2  Average realized gold price ($/oz)   $2,193
3             Total cash costs ($/oz)   $1,014
4      All-in sustaining costs ($/oz)   $1,239
DataFrame 7 - Columnas seleccionadas: ['nombre de la métrica', 'Q1 2024']
             nombre de la métrica  Q1 2024
0                  Gold sold (oz)  111,642
1  Gold equivalent sold (oz AuEq)  114,199
2      Realized gold price ($/oz)   $2,023
3         Total cash costs ($/oz)     $918
4  All-in sustaining costs ($/oz)   $1,202
DataFrame 8 - Columnas seleccionadas: ['Métrica']
                              Métrica
0                     Gold sold (koz)
1     Gold equivalent sold (koz AuEq)
2  Average realized gold price ($/oz)
3             Total cash costs ($/oz)
4      All-in sustaining costs ($/oz)
DataFrame 9 - Columnas seleccionadas: ['Metric', 'Q1 2021']
                          Metric  Q1 2021
0                 Gold sold (oz)  129,019
1     Realized gold price ($/oz)   $1,778
2           Cost of sales ($/oz)   $1,022
3         Total cash cost ($/oz)     $580
4  All-in sustaining cost ($/oz)     $854
DataFrame 10 - Columnas seleccionadas: ['nombre de la métrica', 'Q2 2021']
            nombre de la métrica  Q2 2021
0                 Gold sold (oz)  111,424
1     Realized gold price ($/oz)   $1,816
2           Cost of sales ($/oz)   $1,074
3         Total cash cost ($/oz)     $637
4  All-in sustaining cost ($/oz)     $897
DataFrame 11 - Columnas seleccionadas: ['Metric', 'Q3 2021']
                          Metric  Q3 2021
0                 Gold sold (oz)  118,989
1     Realized gold price ($/oz)   $1,786
2           Cost of sales ($/oz)   $1,198
3         Total cash cost ($/oz)     $727
4  All-in sustaining cost ($/oz)     $900
DataFrame 12 - Columnas seleccionadas: ['Métrica', 'Q4 2023']
                          Métrica  Q4 2023
0                  Gold sold (oz)  138,794
1      Realized gold price ($/oz)   $1,995
2            Cost of sales ($/oz)   $1,368
3         Total cash costs ($/oz)     $885
4  All-in sustaining costs ($/oz)   $1,073
DataFrame 13 - Columnas seleccionadas: ['Metric Name', 'Q1 2022']
                     Metric Name  Q1 2022
0                 Gold sold (oz)  108,012
1     Realized gold price ($/oz)   $1,876
2           Cost of sales ($/oz)   $1,224
3         Total cash cost ($/oz)     $748
4  All-in sustaining cost ($/oz)   $1,034
DataFrame 14 - Columnas seleccionadas: ['nombre de la métrica', 'Q2 2022']
             nombre de la métrica  Q2 2022
0                  Gold sold (oz)  123,363
1      Realized gold price ($/oz)   $1,865
2            Cost of sales ($/oz)   $1,132
3         Total cash costs ($/oz)     $703
4  All-in sustaining costs ($/oz)     $911
DataFrame 15 - Columnas seleccionadas: ['nombre', 'Q2 2023']
                           nombre  Q2 2023
0                  Gold sold (oz)  105,749
1      Realized gold price ($/oz)   $1,960
2            Cost of sales ($/oz)   $1,306
3         Total cash costs ($/oz)     $848
4  All-in sustaining costs ($/oz)   $1,308
DataFrame 16 - Columnas seleccionadas: ['Métrica', 'Q3 2024']
                              Métrica  Q3 2024
0                      Gold sold (oz)  122,130
1      Gold equivalent sold (oz AuEq)  125,414
2  Average realized gold price ($/oz)   $2,313
3             Total cash costs ($/oz)     $926
4      All-in sustaining costs ($/oz)   $1,101

In [3]:
for i in range(len(dfs1)):
    print(i)
    print(dfs1[i].head(2))
    print(dfs1[i]["Metric"])

0
                       Metric  Q4 2021
0              Gold sold (oz)  109,391
1  Realized gold price ($/oz)   $1,798
0                                     Gold sold (oz)
1                         Realized gold price ($/oz)
2                               Cost of sales ($/oz)
3                             Total cash cost ($/oz)
4                      All-in sustaining cost ($/oz)
5                                       Revenue (M$)
6                                        EBITDA (M$)
7                               Adjusted EBITDA (M$)
8                                  Net earnings (M$)
9                         Adjusted net earnings (M$)
10                    Cash flow from operations (M$)
11                         Capital expenditures (M$)
12                               Free cash flow (M$)
13                    Cash and cash equivalents (M$)
14                       Short-term investments (M$)
15                     Debt & Lease Obligations (M$)
16                              Net (debt) cash (M$)
17    Net (debt) cash to EBITDA - Trailing 12 months
Name: Metric, dtype: object
1
                       Metric  Q3 2022
0              Gold sold (oz)  119,834
1  Realized gold price ($/oz)   $1,715
0                      Gold sold (oz)
1          Realized gold price ($/oz)
2                Cost of sales ($/oz)
3             Total cash costs ($/oz)
4      All-in sustaining costs ($/oz)
5                        Revenue (M$)
6                         EBITDA (M$)
7                Adjusted EBITDA (M$)
8              Net income (loss) (M$)
9          Adjusted net earnings (M$)
10     Cash flow from operations (M$)
11          Capital expenditures (M$)
12                Free cash flow (M$)
13     Cash and cash equivalents (M$)
14        Short-term investments (M$)
15      Debt & Lease Obligations (M$)
16               Net (debt) cash (M$)
17    Net (debt) cash to EBITDA - LTM
Name: Metric, dtype: object
2
                       Metric  Q4 2022
0              Gold sold (oz)  121,913
1  Realized gold price ($/oz)   $1,784
0                     Gold sold (oz)
1         Realized gold price ($/oz)
2               Cost of sales ($/oz)
3            Total cash costs ($/oz)
4     All-in sustaining costs ($/oz)
5                       Revenue (M$)
6                        EBITDA (M$)
7               Adjusted EBITDA (M$)
8             Net income (loss) (M$)
9         Adjusted net earnings (M$)
10    Cash flow from operations (M$)
11         Capital expenditures (M$)
12               Free cash flow (M$)
13    Cash and cash equivalents (M$)
14       Short-term investments (M$)
15     Debt & Lease Obligations (M$)
16              Net (debt) cash (M$)
Name: Metric, dtype: object
3
                       Metric Q3 2023
0              Gold sold (oz)  81,752
1  Realized gold price ($/oz)  $1,944
0                                        Gold sold (oz)
1                            Realized gold price ($/oz)
2                                  Cost of sales ($/oz)
3                               Total cash costs ($/oz)
4                        All-in sustaining costs ($/oz)
5                                          Revenue (M$)
6                                           EBITDA (M$)
7                                  Adjusted EBITDA (M$)
8                                Net income (loss) (M$)
9                            Adjusted net earnings (M$)
10                               Income taxes paid (M$)
11    Net cash generated from operating activities (M$)
12                            Capital expenditures (M$)
13                                  Free cash flow (M$)
14                       Cash and cash equivalents (M$)
15                Debt & Lease-Related Obligations (M$)
16                                        Net cash (M$)
Name: Metric, dtype: object
4
                       Metric  Q1 2023
0              Gold sold (oz)  118,455
1  Realized gold price ($/oz)   $1,899
0                     Gold sold (oz)
1         Realized gold price ($/oz)
2               Cost of sales ($/oz)
3            Total cash costs ($/oz)
4     All-in sustaining costs ($/oz)
5                       Revenue (M$)
6                        EBITDA (M$)
7               Adjusted EBITDA (M$)
8             Net income (loss) (M$)
9         Adjusted net earnings (M$)
10            Income taxes paid (M$)
11    Cash flow from operations (M$)
12         Capital expenditures (M$)
13               Free cash flow (M$)
14    Cash and cash equivalents (M$)
15     Debt & Lease Obligations (M$)
16                     Net cash (M$)
Name: Metric, dtype: object
5
                           Metric  Q2 2024
0                  Gold sold (oz)  113,513
1  Gold equivalent sold (oz AuEq)  115,890
0                                        Gold sold (oz)
1                        Gold equivalent sold (oz AuEq)
2                    Average realized gold price ($/oz)
3                               Total cash costs ($/oz)
4                        All-in sustaining costs ($/oz)
5                          Total cash costs ($/oz AuEq)
6                   All-in sustaining costs ($/oz AuEq)
7                                          Revenue (M$)
8                                           EBITDA (M$)
9                                  Adjusted EBITDA (M$)
10                                      Net income (M$)
11                           Adjusted net earnings (M$)
12                               Income taxes paid (M$)
13    Net cash generated from operating activities (M$)
14                            Capital expenditures (M$)
15                                  Free cash flow (M$)
16                       Cash and cash equivalents (M$)
17                       Lease-related obligations (M$)
18                                            Debt (M$)
19                                 Net (debt) cash (M$)
20                             Available Liquidity (M$)
Name: Metric, dtype: object
6
                           Metric  Q1 2024
0                  Gold sold (oz)  111,642
1  Gold equivalent sold (oz AuEq)  114,199
0                                        Gold sold (oz)
1                        Gold equivalent sold (oz AuEq)
2                            Realized gold price ($/oz)
3                               Total cash costs ($/oz)
4                        All-in sustaining costs ($/oz)
5                          Total cash costs ($/oz AuEq)
6                   All-in sustaining costs ($/oz AuEq)
7                                          Revenue (M$)
8                                           EBITDA (M$)
9                                  Adjusted EBITDA (M$)
10                                      Net income (M$)
11                           Adjusted net earnings (M$)
12                               Income taxes paid (M$)
13    Net cash generated from operating activities (M$)
14                            Capital expenditures (M$)
15                                  Free cash flow (M$)
16                       Cash and cash equivalents (M$)
17                       Lease-related obligations (M$)
18                                        Net cash (M$)
19                             Available Liquidity (M$)
Name: Metric, dtype: object
7
                            Metric
0                  Gold sold (koz)
1  Gold equivalent sold (koz AuEq)
0                                       Gold sold (koz)
1                       Gold equivalent sold (koz AuEq)
2                    Average realized gold price ($/oz)
3                               Total cash costs ($/oz)
4                        All-in sustaining costs ($/oz)
5                          Total cash costs ($/oz AuEq)
6                   All-in sustaining costs ($/oz AuEq)
7                                          Revenue (M$)
8                                           EBITDA (M$)
9                                  Adjusted EBITDA (M$)
10                                      Net income (M$)
11                           Adjusted net earnings (M$)
12                               Income taxes paid (M$)
13    Net cash generated from operating activities (M$)
14                            Capital expenditures (M$)
15                                  Free cash flow (M$)
16                       Cash and cash equivalents (M$)
17                       Lease-related obligations (M$)
18                                            Debt (M$)
19                                 Net (debt) cash (M$)
20                             Available Liquidity (M$)
Name: Metric, dtype: object
8
                       Metric  Q1 2021
0              Gold sold (oz)  129,019
1  Realized gold price ($/oz)   $1,778
0                                     Gold sold (oz)
1                         Realized gold price ($/oz)
2                               Cost of sales ($/oz)
3                             Total cash cost ($/oz)
4                      All-in sustaining cost ($/oz)
5                                       Revenue (M$)
6                                        EBITDA (M$)
7                               Adjusted EBITDA (M$)
8                                  Net earnings (M$)
9                         Adjusted net earnings (M$)
10                    Cash flow from operations (M$)
11                               Free cash flow (M$)
12              Cash and short-term investments (M$)
13                     Debt & Lease Obligations (M$)
14                              Net (cash) debt (M$)
15    Net (cash) debt to EBITDA - Trailing 12 months
Name: Metric, dtype: object
9
                       Metric  Q2 2021
0              Gold sold (oz)  111,424
1  Realized gold price ($/oz)   $1,816
0                                     Gold sold (oz)
1                         Realized gold price ($/oz)
2                               Cost of sales ($/oz)
3                             Total cash cost ($/oz)
4                      All-in sustaining cost ($/oz)
5                                       Revenue (M$)
6                                        EBITDA (M$)
7                               Adjusted EBITDA (M$)
8                                  Net earnings (M$)
9                         Adjusted net earnings (M$)
10                    Cash flow from operations (M$)
11                               Free cash flow (M$)
12              Cash and short-term investments (M$)
13                     Debt & Lease Obligations (M$)
14                              Net (debt) cash (M$)
15    Net (debt) cash to EBITDA - Trailing 12 months
Name: Metric, dtype: object
10
                       Metric  Q3 2021
0              Gold sold (oz)  118,989
1  Realized gold price ($/oz)   $1,786
0                                     Gold sold (oz)
1                         Realized gold price ($/oz)
2                               Cost of sales ($/oz)
3                             Total cash cost ($/oz)
4                      All-in sustaining cost ($/oz)
5                                       Revenue (M$)
6                                        EBITDA (M$)
7                               Adjusted EBITDA (M$)
8                                  Net earnings (M$)
9                         Adjusted net earnings (M$)
10                    Cash flow from operations (M$)
11                               Free cash flow (M$)
12              Cash and short-term investments (M$)
13                     Debt & Lease Obligations (M$)
14                              Net (debt) cash (M$)
15    Net (debt) cash to EBITDA - Trailing 12 months
Name: Metric, dtype: object
11
                       Metric  Q4 2023
0              Gold sold (oz)  138,794
1  Realized gold price ($/oz)   $1,995
0                                        Gold sold (oz)
1                            Realized gold price ($/oz)
2                                  Cost of sales ($/oz)
3                               Total cash costs ($/oz)
4                        All-in sustaining costs ($/oz)
5                                          Revenue (M$)
6                                           EBITDA (M$)
7                                  Adjusted EBITDA (M$)
8                                       Net income (M$)
9                            Adjusted net earnings (M$)
10                               Income taxes paid (M$)
11    Net cash generated from operating activities (M$)
12                            Capital expenditures (M$)
13                                  Free cash flow (M$)
14                       Cash and cash equivalents (M$)
15                       Lease-related obligations (M$)
16                                        Net cash (M$)
17                             Available Liquidity (M$)
Name: Metric, dtype: object
12
                       Metric  Q1 2022
0              Gold sold (oz)  108,012
1  Realized gold price ($/oz)   $1,876
0                                     Gold sold (oz)
1                         Realized gold price ($/oz)
2                               Cost of sales ($/oz)
3                             Total cash cost ($/oz)
4                      All-in sustaining cost ($/oz)
5                                       Revenue (M$)
6                                        EBITDA (M$)
7                               Adjusted EBITDA (M$)
8                             Net income (loss) (M$)
9                         Adjusted net earnings (M$)
10                    Cash flow from operations (M$)
11                         Capital expenditures (M$)
12                               Free cash flow (M$)
13                    Cash and cash equivalents (M$)
14                       Short-term investments (M$)
15                     Debt & Lease Obligations (M$)
16                              Net (debt) cash (M$)
17    Net (debt) cash to EBITDA - Trailing 12 months
Name: Metric, dtype: object
13
                       Metric  Q2 2022
0              Gold sold (oz)  123,363
1  Realized gold price ($/oz)   $1,865
0                                     Gold sold (oz)
1                         Realized gold price ($/oz)
2                               Cost of sales ($/oz)
3                            Total cash costs ($/oz)
4                     All-in sustaining costs ($/oz)
5                                       Revenue (M$)
6                                        EBITDA (M$)
7                               Adjusted EBITDA (M$)
8                             Net income (loss) (M$)
9                         Adjusted net earnings (M$)
10                    Cash flow from operations (M$)
11                         Capital expenditures (M$)
12                               Free cash flow (M$)
13                    Cash and cash equivalents (M$)
14                       Short-term investments (M$)
15                     Debt & Lease Obligations (M$)
16                              Net (debt) cash (M$)
17    Net (debt) cash to EBITDA - Trailing 12 months
Name: Metric, dtype: object
14
                       Metric  Q2 2023
0              Gold sold (oz)  105,749
1  Realized gold price ($/oz)   $1,960
0                                        Gold sold (oz)
1                            Realized gold price ($/oz)
2                                  Cost of sales ($/oz)
3                               Total cash costs ($/oz)
4                        All-in sustaining costs ($/oz)
5                                          Revenue (M$)
6                                           EBITDA (M$)
7                                  Adjusted EBITDA (M$)
8                                Net income (loss) (M$)
9                            Adjusted net earnings (M$)
10                               Income taxes paid (M$)
11    Net cash generated from operating activities (M$)
12                            Capital expenditures (M$)
13                                  Free cash flow (M$)
14                       Cash and cash equivalents (M$)
15                Debt & Lease-Related Obligations (M$)
16                                        Net cash (M$)
Name: Metric, dtype: object
15
                           Metric  Q3 2024
0                  Gold sold (oz)  122,130
1  Gold equivalent sold (oz AuEq)  125,414
0                                        Gold sold (oz)
1                        Gold equivalent sold (oz AuEq)
2                    Average realized gold price ($/oz)
3                               Total cash costs ($/oz)
4                        All-in sustaining costs ($/oz)
5                          Total cash costs ($/oz AuEq)
6                   All-in sustaining costs ($/oz AuEq)
7                                          Revenue (M$)
8                                           EBITDA (M$)
9                                  Adjusted EBITDA (M$)
10                                      Net income (M$)
11                           Adjusted net earnings (M$)
12                               Income taxes paid (M$)
13    Net cash generated from operating activities (M$)
14                            Capital expenditures (M$)
15                                  Free cash flow (M$)
16                       Cash and cash equivalents (M$)
17                       Lease-related obligations (M$)
18                                            Debt (M$)
19                                 Net (debt) cash (M$)
20                             Available Liquidity (M$)
Name: Metric, dtype: object

In [4]:

#Edfs_alineados = [df.set_index("Metric") for df in dfs1]
##df_concat = pd.concat(dfs_alineados, axis=1)
#df_concat.head()

# Concatenar los DataFrames de dfs1 de forma horizontal (por columnas)
df_concat = pd.concat(dfs1, axis=1)

# Mostrar las primeras filas del DataFrame resultante
df_concat.head()

,Metric,Q4 2021,Metric,Q3 2022,Metric,Q4 2022,Metric,Q3 2023,Metric,Q1 2023,...,Metric,Q4 2023,Metric,Q1 2022,Metric,Q2 2022,Metric,Q2 2023,Metric,Q3 2024
0,Gold sold (oz),"109,391",Gold sold (oz),"119,834",Gold sold (oz),"121,913",Gold sold (oz),"81,752",Gold sold (oz),"118,455",...,Gold sold (oz),"138,794",Gold sold (oz),"108,012",Gold sold (oz),"123,363",Gold sold (oz),"105,749",Gold sold (oz),"122,130"
1,Realized gold price ($/oz),"$1,798",Realized gold price ($/oz),"$1,715",Realized gold price ($/oz),"$1,784",Realized gold price ($/oz),"$1,944",Realized gold price ($/oz),"$1,899",...,Realized gold price ($/oz),"$1,995",Realized gold price ($/oz),"$1,876",Realized gold price ($/oz),"$1,865",Realized gold price ($/oz),"$1,960",Gold equivalent sold (oz AuEq),"125,414"
2,Cost of sales ($/oz),"$1,235",Cost of sales ($/oz),"$1,220",Cost of sales ($/oz),"$1,202",Cost of sales ($/oz),"$1,627",Cost of sales ($/oz),"$1,160",...,Cost of sales ($/oz),"$1,368",Cost of sales ($/oz),"$1,224",Cost of sales ($/oz),"$1,132",Cost of sales ($/oz),"$1,306",Average realized gold price ($/oz),"$2,313"
3,Total cash cost ($/oz),$764,Total cash costs ($/oz),$760,Total cash costs ($/oz),$711,Total cash costs ($/oz),"$1,086",Total cash costs ($/oz),$709,...,Total cash costs ($/oz),$885,Total cash cost ($/oz),$748,Total cash costs ($/oz),$703,Total cash costs ($/oz),$848,Total cash costs ($/oz),$926
4,All-in sustaining cost ($/oz),"$1,079",All-in sustaining costs ($/oz),"$1,059",All-in sustaining costs ($/oz),"$1,034",All-in sustaining costs ($/oz),"$1,450",All-in sustaining costs ($/oz),"$1,079",...,All-in sustaining costs ($/oz),"$1,073",All-in sustaining cost ($/oz),"$1,034",All-in sustaining costs ($/oz),$911,All-in sustaining costs ($/oz),"$1,308",All-in sustaining costs ($/oz),"$1,101"

In [5]:
import re

# Encuentra las columnas que corresponden a trimestres (formato QX YYYY)
quarter_cols = [col for col in df_concat.columns if re.match(r'Q[1-4] \d{4}', str(col))]

# Ordena las columnas de los trimestres cronológicamente
quarter_cols_sorted = sorted(
    quarter_cols,
    key=lambda x: (int(x.split()[1]), int(x.split()[0][1]))
)

# Reordena el DataFrame: primero 'Metric', luego los trimestres ordenados, luego el resto
cols_order = (
    ['Metric'] +
    quarter_cols_sorted 
)
df_concat = df_concat[cols_order]

In [6]:
df_concat.head()

,Metric,Metric,Metric,Metric,Metric,Metric,Metric,Metric,Metric,Metric,...,Q2 2022,Q3 2022,Q4 2022,Q1 2023,Q2 2023,Q3 2023,Q4 2023,Q1 2024,Q2 2024,Q3 2024
0,Gold sold (oz),Gold sold (oz),Gold sold (oz),Gold sold (oz),Gold sold (oz),Gold sold (oz),Gold sold (oz),Gold sold (koz),Gold sold (oz),Gold sold (oz),...,"123,363","119,834","121,913","118,455","105,749","81,752","138,794","111,642","113,513","122,130"
1,Realized gold price ($/oz),Realized gold price ($/oz),Realized gold price ($/oz),Realized gold price ($/oz),Realized gold price ($/oz),Gold equivalent sold (oz AuEq),Gold equivalent sold (oz AuEq),Gold equivalent sold (koz AuEq),Realized gold price ($/oz),Realized gold price ($/oz),...,"$1,865","$1,715","$1,784","$1,899","$1,960","$1,944","$1,995","114,199","115,890","125,414"
2,Cost of sales ($/oz),Cost of sales ($/oz),Cost of sales ($/oz),Cost of sales ($/oz),Cost of sales ($/oz),Average realized gold price ($/oz),Realized gold price ($/oz),Average realized gold price ($/oz),Cost of sales ($/oz),Cost of sales ($/oz),...,"$1,132","$1,220","$1,202","$1,160","$1,306","$1,627","$1,368","$2,023","$2,193","$2,313"
3,Total cash cost ($/oz),Total cash costs ($/oz),Total cash costs ($/oz),Total cash costs ($/oz),Total cash costs ($/oz),Total cash costs ($/oz),Total cash costs ($/oz),Total cash costs ($/oz),Total cash cost ($/oz),Total cash cost ($/oz),...,$703,$760,$711,$709,$848,"$1,086",$885,$918,"$1,014",$926
4,All-in sustaining cost ($/oz),All-in sustaining costs ($/oz),All-in sustaining costs ($/oz),All-in sustaining costs ($/oz),All-in sustaining costs ($/oz),All-in sustaining costs ($/oz),All-in sustaining costs ($/oz),All-in sustaining costs ($/oz),All-in sustaining cost ($/oz),All-in sustaining cost ($/oz),...,$911,"$1,059","$1,034","$1,079","$1,308","$1,450","$1,073","$1,202","$1,239","$1,101"